name: 
    chromatin_information
channels:
    - conda-forge
    - bioconda
    - r
    - defaults
dependencies:
    # main
    - python=3.5.3
    - r=3.5.1
    
    # sw
    - samtools=1.9
    - bedtools=2.26.0
    - snakemake=5.5.0
    # - bioconda-rgt=0.12.1
    
    # r packages
    - r-data.table=1.12.0
    - r-gridExtra=2.2.1
    - r-reshape2=1.4.2
    - r-ggplot2=2.2.1
    - r-scales=0.5.0
    - r-ggpubr=0.1.6
    - r-dplyr=0.7.8
    - r-readr=1.1.1
    - r-tidyr=0.8.2
    - r-Hmisc=4.0.3
    - r-RColorBrewer=1.1.2
    - r-PRROC=1.3.1
    - r-ROCR=1.0-7
    - r-MASS=7.3-50
    
    # python packages
    - pysam=0.15.2
    # - atactk=0.1.9

    # ngsplot R dependencies
    - r-caTools=1.17.1.1
    - r-doMC=1.3.5
    - bioconductor-Rsamtools=1.34.0
    - bioconductor-BSgenome=1.50.0
    - bioconductor-shortread=1.40.0
